/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with $1$ and $2$, the first $10$ terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.*/

#include <stdio.h>

int	fibonacci_even(int n)
{
	int	res;
	int	prev;
	int	curr;
	int	next;

	res = 0;
	prev = 0;
	curr = 1;
	while (curr < n)
	{
		next = prev + curr;
		prev = curr;
		curr = next;
		if (curr % 2 == 0)
			res += curr;
	}
	return (res);
}

int	main(void)
{
	int	x;

	x = fibonacci_even(4e6);
	printf("Result: %i\n", x);
	return (0);
}
